### ISSUE TITLE
image blur when user stretch

### ISSUE THREAD

**Issue by AmjadKhan2k18** [diegoveloper/flutter_stretchy_header#1]
is it possible when user stretch screen and image doesn't get blur ? 
![strtchyheader](https://user-images.githubusercontent.com/44894621/53936964-6f392480-40cd-11e9-9803-d0700d72c31f.png)

**Comment by diegoveloper** [comment]
Yes, I will work on that.

**Comment by diegoveloper** [comment]
new version (1.0.4) is available, try using  

```
StretchyHeader(
          blurContent: false,
          ...

```
And let me know if it works for you.

**Comment by AmjadKhan2k18** [comment]
Before Stretch 

![isb unstrecthed](https://user-images.githubusercontent.com/44894621/54011867-dfab7880-4195-11e9-9e27-511db2bbce64.png)

after stretch 
![isb stretched](https://user-images.githubusercontent.com/44894621/54011864-de7a4b80-4195-11e9-9357-8177c9d63371.png)

i was thinking if we can do something similar like this ? its SilverCar App. 
![e4e5b266-160e-4c19-9c5f-fe119b5d60c9](https://user-images.githubusercontent.com/44894621/54011926-15e8f800-4196-11e9-9934-f93995c88fb8.jpg)

![stretched](https://user-images.githubusercontent.com/44894621/54011928-16818e80-4196-11e9-9bcc-9e6be82fb0c3.jpg)

**Comment by diegoveloper** [comment]
Use the highlightHeader property from Sample 3 (put the title widget there) : https://pub.dartlang.org/packages/stretchy_header
