### ISSUE TITLE
GestureDetector onTap event not called inside header widget

### ISSUE THREAD

**Issue by danielhakimi** [diegoveloper/flutter_stretchy_header#2]
Hi, awesome package btw.

I'm trying to place a GestureDetector inside the StretchyHeader header widget, but something is swallowing the call. If I place a GestureDetector around the StrectchyHeader it works, but then it's called for the whole view. Any ideas about why that might be happening?

Thanks

**Comment by diegoveloper** [comment]
Please , add a simple code to reproduce the issue.

Thanks

**Comment by danielhakimi** [comment]
`Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: StretchyHeader(
          headerHeight: 250.0,
          blurContent: false,
          header: Stack(fit: StackFit.expand, children: [
            Image.asset('assets/ic_rocks_bg.png', fit: BoxFit.cover),
            GestureDetector(
                onTap: () => print('event not called!!!'),
                child: CircleAvatar())
          ]),
          body: ListView.builder(
            itemCount: 15,
            shrinkWrap: true,
            itemBuilder: (context, index) {
              return ListTile(
                title: Text("item $index"),
              );
            },
          ),
        ),
      ),
    );
  }`

**Comment by diegoveloper** [comment]
You can use the `highlightHeader` and `highlightHeaderAlignment` property, like this sample :

```
@override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: StretchyHeader(
          headerHeight: 250.0,
          highlightHeaderAlignment: HighlightHeaderAlignment.center,
          highlightHeader: GestureDetector(
            onTap: () => print('event called!!!'),
            child: Container(
              width: MediaQuery.of(context).size.width,
              child: CircleAvatar(
                radius: 40,
              ),
            ),
          ),
          header: Image.asset(
            "assets/ic_rocks_bg.png",
            fit: BoxFit.cover,
          ),
          body: ListView.builder(
            itemCount: 15,
            shrinkWrap: true,
            itemBuilder: (context, index) {
              return ListTile(
                title: Text("item $index"),
              );
            },
          ),
        ),
      ),
    );
  }
```

**Comment by danielhakimi** [comment]
Thanks!
