### ISSUE TITLE
GestureDetector onTap event not called inside body widget

### ISSUE THREAD

**Issue by samigimix** [diegoveloper/flutter_stretchy_header#3]
Hi, awesome package btw.

I'm trying to place a GestureDetector inside the StretchyHeader body widget, but something is swallowing the call. Any ideas about why that might be happening?

```
return SafeArea(
      child: Scaffold(
        body: StretchyHeader(
          headerHeight: 250.0,
          header: Image.asset(
            "assets/hol.jpg",
            fit: BoxFit.cover,
          ),
          body: ListView.builder(
            itemCount: 15,
            shrinkWrap: true,
            itemBuilder: (context, index) {
              return ListTile(
                title: GestureDetector(
                  child: Container(
                    color: Colors.blue,
                    height: 10,
                  ),
                  onTap: () {
                    print('object');
                  },
                ),
              );
            },
          ),
        ),
      ),
    );
```

**Comment by diegoveloper** [comment]
Hi, check this closed issue: https://github.com/diegoveloper/flutter_stretchy_header/issues/2

**Comment by samigimix** [comment]
I did, but my problem is about the body, not the header. Could you help pls?

**Comment by samigimix** [comment]
I want to use GestureDetector in body but it doesn't work, I used highlightHeader too but it didn't work for body widget.

**Comment by diegoveloper** [comment]
The problem using `GestureDetector` inside the body is it won't allow scroll the Widget.

**Comment by samigimix** [comment]
@diegoveloper so how should we handle that? having a streachy header with gesture detector on the body?

**Comment by diegoveloper** [comment]
Give me a few days, I'm out of my country doing some activities now.

**Comment by samigimix** [comment]
I resolved it by _removing_ **`AbsorbPointer`** for **`widget.body`** in `_StretchyHeaderState` class.
